# Generated by Django 5.1.3 on 2024-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamdetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
